export const BASE_URL_LOCAL = 'http://ads.com/api/'
export const BASE_URL_GLOBAL = 'http://api.kositutor.in/api/'
export const PRESENT_TEACHERS = 'PresentTeachers'
export const FOOTER = 'footer'
export const LOGIN = 'token'
export const LOGOUT = 'logout'
export const BLOGS = 'blogs?page='