// Present Teachers
export const REQUEST_PRESENT_TEACHER = "REQUEST_PRESENT_TEACHER";
export const RECEIVE_PRESENT_TEACHER = "RECEIVE_PRESENT_TEACHER";
export const FAILURE_PRESENT_TEACHER = "FAILURE_PRESENT_TEACHER";
// footer
export const REQUEST_FOOTER = "REQUEST_FOOTER";
export const RECEIVE_FOOTER = "RECEIVE_FOOTER";
export const FAILURE_FOOTER = "FAILURE_FOOTER";
// auth
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const FAILURE_LOGIN = "FAILURE_LOGIN";
export const RECEIVE_LOGIN_FROM_SESSION = "RECEIVE_LOGIN_FROM_SESSION"
// blogs
export const REQUEST_BLOGS = 'REQUEST_BLOGS';
export const RECEIVE_BLOGS = 'RECEIVE_BLOGS';
export const FAILURE_BLOGS = 'FAILURE_BLOGS';

// Blog
export const REQUEST_BLOG = 'REQUEST_BLOG'
export const RECEIVE_BLOG = 'RECEIVE_BLOG'
export const FAILURE_BLOG = 'FAILURE_BLOG'

// LOGOUT
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const FAILURE_LOGOUT = 'FAILURE_LOGOUT';

export const REQUEST_LOADING = "REQUEST_LOADING";
export const RECEIVE_LOADING = "RECEIVE_LOADING";

// BIRTHDAY
export const REQUEST_BIRTHDAY = 'REQUEST_BIRTHDAY';
export const RECEIVE_BIRTHDAY = 'RECEIVE_BIRTHDAY';
export const FAILURE_BIRTHDAY = 'FAILURE_BIRTHDAY';
// contact us
export const REQUEST_CONTACT_US = 'REQUEST_CONTACT_US';
export const RECEIVE_CONTACT_US = 'RECEIVE_CONTACT_US';
export const FAILURE_CONTACT_US = 'FAILURE_CONTACT_US';

// contactus post
export const REQUEST_CONTACT_US_POST = 'REQUEST_CONTACT_US_POST';
export const RECEIVE_CONTACT_US_POST = 'RECEIVE_CONTACT_US_POST';
export const FAILURE_CONTACT_US_POST = 'FAILURE_CONTACT_US_POST';

//get list of student
export const REQUEST_STUDENT_LIST = 'REQUEST_STUDENT_LIST';
export const RECEIVE_STUDENT_LIST = 'RECEIVE_STUDENT_LIST';
export const FAILURE_STUDENT_LIST = 'FAILURE_STUDENT_LIST';

// get std list
export const REQUEST_STD_LIST = 'REQUEST_STD_LIST'
export const RECEIVE_STD_LIST = 'RECEIVE_STD_LIST'
export const FAILURE_STD_LIST = 'FAILURE_STD_LIST'

// update std id
export const REQUEST_UPDATE_STD_ID = 'REQUEST_UPDATE_STD_ID'
export const RECEIVE_UPDATE_STD_ID = 'RECEIVE_UPDATE_STD_ID'

// count
export const REQUEST_COUNT_STUDENT = 'REQUEST_COUNT_STUDENT'
export const RECEIVE_COUNT_STUDENT = 'RECEIVE_COUNT_STUDENT'
export const FAILURE_COUNT_STUDENT = 'FAILURE_COUNT_STUDENT'
export const REQUEST_COUNT_TEACHER = 'REQUEST_COUNT_TEACHER'
export const RECEIVE_COUNT_TEACHER = 'RECEIVE_COUNT_TEACHER'
export const FAILURE_COUNT_TEACHER = 'FAILURE_COUNT_TEACHER'
export const REQUEST_COUNT_ADMIN = 'REQUEST_COUNT_ADMIN'
export const RECEIVE_COUNT_ADMIN = 'RECEIVE_COUNT_ADMIN'
export const FAILURE_COUNT_ADMIN = 'FAILURE_COUNT_ADMIN'
export const REQUEST_COUNT_NONTEACHING = 'REQUEST_COUNT_NONTEACHING'
export const RECEIVE_COUNT_NONTEACHING = 'RECEIVE_COUNT_NONTEACHING'
export const FAILURE_COUNT_NONTEACHING = 'FAILURE_COUNT_NONTEACHING'
export const REQUEST_POST_MESSAGE = 'REQUEST_POST_MESSAGE'
export const RECEIVE_POST_MESSAGE = 'RECEIVE_POST_MESSAGE'
export const FAILURE_POST_MESSAGE = 'FAILURE_POST_MESSAGE'

// Page
export const REQUEST_PAGE_SETUP = 'REQUEST_PAGE_SETUP'
// notifi
export const REQUEST_ADD_NOTIFI_USER='REQUEST_ADD_NOTIFI_USER'
export const REQUEST_REMOVE_NOTIFI_USER ='REQUEST_REMOVE_NOTIFI_USER'

// Comment
export const REQUEST_COMMENT_POST = 'REQUEST_COMMENT_POST'
export const RECEIVE_COMMENT_POST = 'RECEIVE_COMMENT_POST'
export const FAILURE_COMMENT_POST = 'FAILURE_COMMENT_POST'

// balance
export const REQUEST_BALANCE = 'REQUEST_BALANCE'
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE'
export const FAILURE_BALANCE = 'FAILURE_BALANCE'

// user search
export const REQUEST_USER_SEARCH = 'REQUEST_USER_SEARCH'
export const RECEIVE_USER_SEARCH = 'RECEIVE_USER_SEARCH'
export const FAILURE_USER_SEARCH = 'FAILURE_USER_SEARCH'
export const REQUEST_USER_SELECT = 'REQUEST_SELECT_ITEM'

// user
export const REQUEST_ADD_USER = 'REQUEST_ADD_USER'
export const RECEIVE_ADD_USER = 'RECEIVE_ADD_USER'
export const FAILURE_ADD_USER = 'FAILURE_ADD_USER'

// gender
export const REQUEST_GET_GENDER = 'REQUEST_GET_GENDER'
export const RECEIVE_GET_GENDER = 'RECEIVE_GET_GENDER'
export const FAILURE_GET_GENDER = 'FAILURE_GET_GENDER'

// contacttypes
export const REQUEST_GET_CONTACT_TYPE = 'REQUEST_GET_CONTACT_TYPE'
export const RECEIVE_GET_CONTACT_TYPE = 'RECEIVE_GET_CONTACT_TYPE'
export const FAILURE_GET_CONTACT_TYPE = 'FAILURE_GET_CONTACT_TYPE'

// addresstype
export const REQUEST_GET_ADDRESS_TYPE = 'REQUEST_GET_ADDRESS_TYPE'
export const RECEIVE_GET_ADDRESS_TYPE = 'RECEIVE_GET_ADDRESS_TYPE'
export const FAILURE_GET_ADDRESS_TYPE = 'FAILURE_GET_ADDRESS_TYPE'

// relations
export const REQUEST_RELATION = 'REQUEST_RELATION'
export const RECEIVE_RELATION = 'RECEIVE_RELATION'
export const FAILURE_RELATION = 'FAILURE_RELATION'

// pins
export const REQUEST_STATES = 'REQUEST_STATES'
export const RECEIVE_STATES = 'RECEIVE_STATES'
export const FAILURE_STATES = 'FAILURE_STATES'
export const REQUEST_DISTRICTS = 'REQUEST_DISTRICTS'
export const RECEIVE_DISTRICTS = 'RECEIVE_DISTRICTS'
export const FAILURE_DISTRICTS = 'FAILURE_DISTRICTS'
export const REQUEST_PINS = 'REQUEST_PINS'
export const RECEIVE_PINS = 'RECEIVE_PINS'
export const FAILURE_PINS = 'FAILURE_PINS'

// transport
export const REQUEST_TRANSPORT = 'REQUEST_TRANSPORT'
export const RECEIVE_TRANSPORT = 'RECEIVE_TRANSPORT'
export const FAILURE_TRANSPORT = 'FAILURE_TRANSPORT'

// scholor
export const REQUEST_SCHOLOR = 'REQUEST_SCHOLOR'
export const RECEIVE_SCHOLOR = 'RECEIVE_SCHOLOR'
export const FAILURE_SCHOLOR = 'FAILURE_SCHOLOR'

// add student
export const REQUEST_ADD_STUDENT = 'REQUEST_ADD_STUDENT'
export const RECEIVE_ADD_STUDENT = 'RECEIVE_ADD_STUDENT'
export const FAILURE_ADD_STUDENT = 'FAILURE_ADD_STUDENT'

// parent
export const REQUEST_PARENT = 'REQUEST_PARENT'
export const RECEIVE_PARENT = 'RECEIVE_PARENT'
export const FAILURE_PARENT = 'FAILURE_PARENT'

// Address
export const REQUEST_ADD_ADDRESS = 'REQUEST_ADD_ADDRESS'
export const RECEIVE_ADD_ADDRESS = 'RECEIVE_ADD_ADDRESS'
export const FAILURE_ADD_ADDRESS = 'FAILURE_ADD_ADDRESS'

// Contact
export const REQUEST_ADD_CONTACT = 'REQUEST_ADD_CONTACT'
export const RECEIVE_ADD_CONTACT = 'RECEIVE_ADD_CONTACT'
export const FAILURE_ADD_CONTACT = 'FAILURE_ADD_CONTACT'

// add document
export const REQUEST_ADD_DOCUMENT = 'REQUEST_ADD_DOCUMENT'
export const RECEIVE_ADD_DOCUMENT = 'RECEIVE_ADD_DOCUMENT'
export const FAILURE_ADD_DOCUMENT = 'FAILURE_ADD_DOCUMENT'

// progress
export const REQUEST_UPDATE_PROGRESS = 'REQUEST_UPDATE_PROGRESS'

// update document
export const REQUEST_GET_TEACHER = 'REQUEST_GET_TEACHER'
export const RECEIVE_GET_TEACHER = 'RECEIVE_GET_TEACHER'
export const FAILURE_GET_TEACHER = 'FAILURE_GET_TEACHER'

// blog post
export const REQUEST_POST_BLOG = 'REQUEST_POST_BLOG'
export const RECEIVE_POST_BLOG = 'RECEIVE_POST_BLOG'
export const FAILURE_POST_BLOG = 'FAILURE_POST_BLOG'