// Present Teachers
export const REQUEST_PRESENT_TEACHER = "REQUEST_PRESENT_TEACHER";
export const RECEIVE_PRESENT_TEACHER = "RECEIVE_PRESENT_TEACHER";
export const FAILURE_PRESENT_TEACHER = "FAILURE_PRESENT_TEACHER";
// footer
export const REQUEST_FOOTER = "REQUEST_FOOTER";
export const RECEIVE_FOOTER = "RECEIVE_FOOTER";
export const FAILURE_FOOTER = "FAILURE_FOOTER";
// auth
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const FAILURE_LOGIN = "FAILURE_LOGIN";
export const RECEIVE_LOGIN_FROM_SESSION = "RECEIVE_LOGIN_FROM_SESSION"
// blogs
export const REQUEST_BLOGS ='REQUEST_BLOGS';
export const RECEIVE_BLOGS ='RECEIVE_BLOGS';
export const FAILURE_BLOGS ='FAILURE_BLOGS';

// LOGOUT
export const REQUEST_LOGOUT ='REQUEST_LOGOUT';
export const RECEIVE_LOGOUT ='RECEIVE_LOGOUT';
export const FAILURE_LOGOUT ='FAILURE_LOGOUT';
//ContactUs
export const REQUEST_CONTACTUS ="REQUEST_CONTACTUS";
export const RECEIVE_CONTACTUS ="RECEIVE_CONTACTUS";
export const FAILURE_CONTACTUS ="FAILURE_CONTACTUS";
//LOADING
export const REQUEST_LOADING ='REQUEST_LOADING';
export const RECEIVE_LOADING ='RECEIVE_LOADING';